### ISSUE TITLE
Don't reference 5MIN in text - use a static to mark it as default

### ISSUE THREAD

**Issue by hochshi** [boazhoch/charts#4]
https://github.com/boazhoch/charts/blob/645464b3f6080bdb309c414c9f987be610a3c3d5/src/services/stock/index.ts#L13

https://github.com/boazhoch/charts/blob/645464b3f6080bdb309c414c9f987be610a3c3d5/src/services/stock/index.ts#L17

https://github.com/boazhoch/charts/blob/645464b3f6080bdb309c414c9f987be610a3c3d5/src/services/stock/index.ts#L57

https://github.com/boazhoch/charts/blob/645464b3f6080bdb309c414c9f987be610a3c3d5/src/services/stock/index.ts#L33

something like:

DEFAULT = "5MIN"
QUERY_INTERVALS[QUERY_INTERVALS.DEFAULT]

same goes for
https://github.com/boazhoch/charts/blob/645464b3f6080bdb309c414c9f987be610a3c3d5/src/components/Chart/Chart.tsx#L104

https://github.com/boazhoch/charts/blob/645464b3f6080bdb309c414c9f987be610a3c3d5/src/components/Chart/Chart.tsx#L156

https://github.com/boazhoch/charts/blob/645464b3f6080bdb309c414c9f987be610a3c3d5/src/components/Chart/Chart.tsx#L225

**Comment by boazhoch** [comment]
@hochshi +1 actually ES6 introduce default parameters, so ill do static props with default paramters

**Comment by hochshi** [comment]
same goes for
https://github.com/boazhoch/charts/blob/645464b3f6080bdb309c414c9f987be610a3c3d5/src/components/Chart/Chart.tsx#L104

https://github.com/boazhoch/charts/blob/645464b3f6080bdb309c414c9f987be610a3c3d5/src/components/Chart/Chart.tsx#L156

https://github.com/boazhoch/charts/blob/645464b3f6080bdb309c414c9f987be610a3c3d5/src/components/Chart/Chart.tsx#L225
